const gearItems = [
    {name: "Long Underwear Tops and Bottoms (Midweight, Synthetic)", level:"Required", price: 65, currentCount: 0},
    {name: "Hiking Pants (Convertible, Quick-Dry, Lightweight)", level:"Required", price: 80, currentCount: 0},
    {name: "Day Pack (21L-35L)", level:"Required", price: 80, currentCount: 0},
    {name: "Rain Jacket (Hooded, Lightweight, Waterproof, Breathable)", level:"Required", price: 100, currentCount: 0},
    {name: "Rain Pants (Lightweight, Waterproof, Breathable)", level:"Required", price: 80, currentCount: 0},
    {name: "Fleece/Wool Jacket or Sweater", level:"Required", price: 120, currentCount: 0},
    {name: "Fleece Pants", level:"Required", price: 80, currentCount: 0},
    {name: "Long Sleeve Shirts (Synthetic, Lightweight)", level:"Required", price: 40, currentCount: 0},
    {name: "Hiking Socks (Synthetic or Wool)", level:"Required", price: 20, currentCount: 0},
    {name: "Sun Hat", level:"Required", price: 50, currentCount: 0},
    {name: "Fleece/Wool Hat", level:"Required", price: 40, currentCount: 0},
    {name: "Fleece/Wool Gloves", level:"Required", price: 50, currentCount: 0},
    {name: "Hiking Boots", level:"Required", price: 200, currentCount: 0},
    {name: "Headlamp with Fresh Batteries", level:"Required", price: 50, currentCount: 0},
    {name: "Day Pack Rain Cover", level:"Required", price: 30, currentCount: 0},
    {name: "Sport Sunglasses", level:"Required", price: 70, currentCount: 0},
    {name: "Sun Block and Lip Balm", level:"Required", price: 30, currentCount: 0},
    {name: "Long Underwear Tops and Bottoms (Heavyweight, Synthetic, Colder Travel Periods)", level:"Required", price: 200, currentCount: 0},
    {name: "Water Bottles (Two 1-Quart) or Hydration System Plus One 1-Quart Water Bottle", level:"Required", price: 100, currentCount: 0},
    {name: "Insulated Jacket", level:"Required", price: 300, currentCount: 0},
    {name: "Duffel Bag (No Wheels or Rigid Frames)", level:"Required", price: 100, currentCount: 0},
    {name: "Sleeping Bag (1°-14°, Lightweight, Compressible)", level:"Required", price: 300, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Recommended", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
    {name: "", level:"Optional", price: 0, currentCount: 0},
];

export default gearItems;