const gearItems = [
    {name: "Long Underwear Tops and Bottoms (Midweight, Synthetic)", level:"Required", price: 65, currentCount: 0},
    {name: "Hiking Pants (Convertible, Quick-Dry, Lightweight)", level:"Required", price: 80, currentCount: 0},
    {name: "Day Pack (21L-35L)", level:"Required", price: 80, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
    {name: "test", price: 0, currentCount: 0},
];

export default gearItems;