const gearItems = [
    {name: "Long Underwear Tops and Bottoms (Midweight, Synthetic)", price: 65, maxCount: 20, currentCount: 0},
    {name: "Hiking Pants (Convertible, Quick-Dry, Lightweight)", price: 80, maxCount: 10, currentCount: 0},
    {name: "Day Pack (21L-35L)", price: 80, maxCount: 4, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
    {name: "test", price: 0, maxCount: 10, currentCount: 0},
];

export default gearItems;